### ISSUE TITLE
LiTS Database

### ISSUE THREAD

**Issue by sudhasubramaniam** [imatge-upc/liverseg-2017-nipsws#1]
LiTS Database is empty. Where can I get the images.

**Comment by miriambellver** [comment]
Hi, 

the information to get the database is in the Data section of the README.

Regards,

Miriam

**Comment by sudhasubramaniam** [comment]
Hi,

I need some clarification regarding data.  The data will be an CT scan
image. How this image is converted into .nii format? While retrieving back
the image you are getting .mat file, what is this .mat file?

Regards,
Sudha
