### ISSUE TITLE
Error in seg_liver.py

### ISSUE THREAD

**Issue by lisa676** [imatge-upc/liverseg-2017-nipsws#10]
I'm getting errors in your work in this file  seg_liver.py, line 552      print ("Model saved in file: %s") % save_path 
TypeError: unsupported operand type(s) for %: 'NonType' and 'str'  

I'm using Python 3.6  It was working fine but at the time of saving path it shows this error. How to recover it?

**Comment by miriambellver** [comment]
I checked online, and if you do the[ following change](https://stackoverflow.com/questions/23372824/typeerror-unsupported-operand-types-for-nonetype-and-str) it will work.

Regards,
Míriam
