### ISSUE TITLE
Skip detection network?

### ISSUE THREAD

**Issue by leetesua** [imatge-upc/liverseg-2017-nipsws#11]
Hi, a little question here. Why you are not directly segmenting the lesion from the segmented liver?  Instead    you first detect a bounding box, and then you segment lesion from it. 
I have tested your liver segment network and achieve a pretty good result. Which means the liver segmenting network is working very well. I am thinking, if I use output liver as a mask to process original data, and use lesion as label, then retrain it on liver segment network. Will it work?

**Comment by miriambellver** [comment]
The liver mask is indeed being used for training the lesion segmentation. We just back-propagate the loss for the lesion training through the liver region, everything is explained in our article. Once the lesion is predicted, it is masked with the liver region as well. Hope it helps!

Regards,

Míriam
