### ISSUE TITLE
#s at the end of each line for testing_volume_3.txt

### ISSUE THREAD

**Issue by michaeltlu** [imatge-upc/liverseg-2017-nipsws#14]
Thanks for publishing this code.

A question -- what are the two numbers at the end of each line for the testing_volume_3.txt file? I can see that they are the same for every set of images for a given CT scan. For example:

images_volumes/105/1.mat item_seg/105/1.png liver_seg/105/1.png images_volumes/105/2.mat item_seg/105/2.png liver_seg/105/2.png images_volumes/105/3.mat item_seg/105/3.png liver_seg/105/3.png 0.000132 0.028108

**Comment by miriambellver** [comment]
Hi!

These are two numbers that I didn't use for the final implementation. Basically the first number is the number of voxels that belong to lesion class divided by the total volume, and the second number is the same but for the liver class. These numbers are not used anywhere in the code though.

Míriam

**Comment by michaeltlu** [comment]
Great thanks. I appreciate the quick response.

**Comment by dyl0101** [comment]
> Hi!
> 
> These are two numbers that I didn't use for the final implementation. Basically the first number is the number of voxels that belong to lesion class divided by the total volume, and the second number is the same but for the liver class. These numbers are not used anywhere in the code though.
> 
> Míriam

Hello！

Thank you very much for your answer, but I want to know whether these two numbers in the tumor test file ‘testing_volume_3_crops.txt’ are not used, if those two numbers are useless, why do I get the following error when I When I tested the tumor segmentation network on 70 test data:

File "/home/dyl/liverseg-2017-nipsws-master/dataset/dataset_seg_1.py", line 112, in __init__
    aux_images_test_path.append(os.path.join(database_root, str(line.split()[i * 3])))

IndexError: list index out of range

Look forward to your reply！thanks
