### ISSUE TITLE
About  testing_volume_3_crops.txt

### ISSUE THREAD

**Issue by dyl0101** [imatge-upc/liverseg-2017-nipsws#28]
> 
    Hi!

    These are two numbers that I didn't use for the final implementation. Basically the first number is the number of voxels that belong to lesion class divided by the total volume, and the second number is the same but for the liver class. These numbers are not used anywhere in the code though.

    Míriam

> 

Hello！

Thank you very much for your answer, but I want to know whether these two numbers in the tumor test file ‘testing_volume_3_crops.txt’ are not used, if those two numbers are useless, why do I get the following error when I When I tested the tumor segmentation network on 70 test data:

File "/home/dyl/liverseg-2017-nipsws-master/dataset/dataset_seg_1.py", line 112, in init
aux_images_test_path.append(os.path.join(database_root, str(line.split()[i * 3])))

IndexError: list index out of range

Look forward to your reply！thanks

**Comment by lesliewubbel** [comment]
did you figure anything out?

**Comment by miriambellver** [comment]
This is just an issue when reading the file, this does not mean that the numbers are actually used when training the model. If you want to use the dataset_seg code, then generate a file that has the same format (same number of elements per line in the text file, even if they are dummy values). An alternative is to change the dataset_seg code to get lines that have a single value per line.
