### ISSUE TITLE
Are the TXT files made manually or in the code?

### ISSUE THREAD

**Issue by rishyak** [imatge-upc/liverseg-2017-nipsws#29]
Hi,
I'm trying to run this model to see how it works. I can't figure out if the TXT files (training_volume_3.txt, testing_volume_3.txt) were made manually or they were made somewhere in the code. 

Thank you.

**Comment by miriambellver** [comment]
The code to do them is not in the repo.

**Comment by rishyak** [comment]
Could you give me a brief logic behind the txt files so I can make a script to do that for me?

**Comment by miriambellver** [comment]
We are already giving this information in the repository main README: https://github.com/imatge-upc/liverseg-2017-nipsws#liver-segmentation . Please, read the instructions before using the code.
