### ISSUE TITLE
Question about nonexistent layers in modified VGG16 convnets

### ISSUE THREAD

**Issue by philferriere** [imatge-upc/liverseg-2017-nipsws#5]
The liver and lesion segmenters refer to a `conv3d` layer in the `parameter_lr()` function, as shown below:

``` python
    vars_corresp['seg_lesion/conv3d_1/weights'] = 1
    vars_corresp['seg_lesion/conv3d_1/biases'] = 2
    vars_corresp['seg_lesion/conv3d_2/weights'] = 1
    vars_corresp['seg_lesion/conv3d_2/biases'] = 2
    vars_corresp['seg_lesion/conv3d_3/weights'] = 1
    vars_corresp['seg_lesion/conv3d_3/biases'] = 2
    vars_corresp['seg_lesion/conv3d_4/weights'] = 1
    vars_corresp['seg_lesion/conv3d_4/biases'] = 2
```
and
``` python
    vars_corresp['seg_liver/conv3d_1/weights'] = 1
    vars_corresp['seg_liver/conv3d_1/biases'] = 2
    vars_corresp['seg_liver/conv3d_2/weights'] = 1
    vars_corresp['seg_liver/conv3d_2/biases'] = 2
    vars_corresp['seg_liver/conv3d_3/weights'] = 1
    vars_corresp['seg_liver/conv3d_3/biases'] = 2
    vars_corresp['seg_liver/conv3d_4/weights'] = 1
    vars_corresp['seg_liver/conv3d_4/biases'] = 2
```

These layers doen't seem to exist in the network code definitions nor in the checkpoints provided at https://mega.nz/#!1r4XmDaB!9SPxHxMh1eYGzxtJzKN-CTkODibYOxkxjoBY2gWVaFQ.

Is it safe to assume that this is, perhaps, the remnant of an experiment and that this code can be simply removed?

Again, thank you for your great work and taking the time to answer my questions!

**Comment by miriambellver** [comment]
yes, exactly, these are from a prior experiment that we did. But the code should work anyways. Thanks for noticing!
