### ISSUE TITLE
liverseg

### ISSUE THREAD

**Issue by superrui0810** [imatge-upc/liverseg-2017-nipsws#6]
If the liver is incomplete, can this model be detected?

**Comment by superrui0810** [comment]
If the liver is incomplete due to surgical cutting, can this model be accurately segmented?

**Comment by miriambellver** [comment]
Hi,

If you have an annotated dataset of livers with surgical cutting together with standard livers, and you train the model for that, it should work properly. 

Regards,

Míriam

**Comment by superrui0810** [comment]
Much appreciated!
