### ISSUE TITLE
liverseg

### ISSUE THREAD

**Issue by mitiandi** [imatge-upc/liverseg-2017-nipsws#7]
Hi,
It is such a quite awesome work that I want to make it as a benchmark in my research. But the loss has been   
fluctuating when I run the "liver_seg_train.py". It is even the same dataset and folder structure. It confused
me for a long time and I can not find the mistake anywhere. Could you give me some good suggestions?
thank you!

**Comment by miriambellver** [comment]
The loss may fluctuate, because the batches are of a single slice each time, but even if the loss is noisy, it decreases and it is learning. I recommend you that you check visually the results to see what is happening.

Míriam

**Comment by mitiandi** [comment]
Thanks for your kind response and suggestion!
