### ISSUE TITLE
wrong result when test the dataset using the model gave

### ISSUE THREAD

**Issue by legendhua** [imatge-upc/liverseg-2017-nipsws#8]
hello , I am appreciate that you provide source code. When I test the LiTS test dataset with the model you gave directly, why did I get erroneous results and I thought it is wrong result.

**Comment by miriambellver** [comment]
What kind of result do you obtain?

**Comment by dhuminhaz** [comment]
Hello, I send you a mail. I am waiting to your kind response.

**Comment by legendhua** [comment]
@miriambellver thanks,  all black background test pictures and i don't know what happened. Then I train myself and get a model that can seg liver.

**Comment by lisa676** [comment]
@miriambellver Great work, I want to run this project on Pycharm and I'm using python 3.6. Is it ok or I will have to change to python 2.7?
