### ISSUE TITLE
dice score

### ISSUE THREAD

**Issue by treisto** [imatge-upc/liverseg-2017-nipsws#9]
Hi Miriam, firstly I want to thank you very much for sharing this work.

I am a student and I am trying to understand how it works. 
Right now I don't understand how you practically compute the liver segmentation dice scores when running the test on the 26 volumes validation set and on the LITS 70 volumes test set. "seg_liver_test.py" seems to output just the 2D slices. Were you converting the output slices to .nii volumes and then use the LITS challenge online/offline dice score assessment code? 

Thank you very much,
Lucian

**Comment by miriambellver** [comment]
Hi!

Yes, the seg_liver_test.py just outputs the 2D slices, then I created a .nii file to finally evaluate the performance on the server.

Regards,
Míriam
